version: '3'

services:
  web:
    container_name: web
    build: ./docker
    ports:
      - 80:80
    privileged: true
    volumes:
      - .:/var/www/html

  db:
    image: postgres:12.4-alpine
    container_name: postgresql
    ports:
      - 5433:5432
    volumes:
      - ./docker/pgsql/data:/var/lib/pgsql
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: bdgfans
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root

  minio:
    image: minio/minio
    volumes:
      - ./docker/minio/data:/export
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: rootroot
      MINIO_SECRET_KEY: rootroot
    command: server /export

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8080:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4