version: 2

jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh -o 'StrictHostKeyChecking no' ${USER_NAME}@${HOST_NAME} 'cd /var/www/bodoge_fans && git pull origin master && yarn run prod'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
              branches:
                  only: master